apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      imagePullSecrets:
          - name: acr-secret
      containers:
        - name: api-gateway
          image: getbetter.azurecr.io/api-gateway:latest
          
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: api-gateway-config
            - secretRef:
                name: api-gateway-secret
          resources:
            requests:
              cpu: 128m
              memory: 128Mi
            limits:
              cpu: 256m
              memory: 256Mi

          # 🟢 **Startup Probe: Ensures the app has started**
          startupProbe:
            httpGet:
              path: /startup
              port: 80
            initialDelaySeconds: 5  # Wait 5 sec before first check
            periodSeconds: 10        # Check every 10 sec
            failureThreshold: 3      # Fail after 3 failed attempts

          # 🟡 **Readiness Probe: Ensures the app is ready for traffic**
          readinessProbe:
            httpGet:
              path: /readyz
              port: 80
            initialDelaySeconds: 5  # Wait 5 sec before first check
            periodSeconds: 5        # Check every 5 sec
            failureThreshold: 2      # Fail if 2 consecutive failures

          # 🔴 **Liveness Probe: Ensures the app is still running**
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3  # Wait 3 sec before first check
            periodSeconds: 5        # Check every 5 sec
            failureThreshold: 2      # Restart pod after 2 failed attempts
