apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-user-service
spec:

  minReplicas: 1
  maxReplicas: 5

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50