apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  USER_ATLAS_URI: bW9uZ29kYitzcnY6Ly9qdWxpdXNub3Jlbjo3QmxWWEJqN1J0dnVHdFJTQGNsdXN0ZXIwLm5qbjc0Lm1vbmdvZGIubmV0L1VzZXI/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=
  SECRET: YmFlc2FyZ3JlYXRlcnRoYW5hc2hiZW5sb2xv
  EMAIL_ADDRESS: aW5mb3JtYXRpb24uZ2V0YmV0dGVyQGdtYWlsLmNvbQ==
  EMAIL_PASSWORD: eXRrZmlwY2lmdGtkdWlqeA==