apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: getbetter.azurecr.io/user-service:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: user-service-config
            - secretRef:
                name: user-service-secret
          resources:
            requests:
              cpu: 5m
              memory: 64Mi
            limits:
              cpu: 20m
              memory: 128Mi
