version: "3.8"

services:
  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - booking-service
    env_file:
      - ./backend/api-gateway/.env

  user-service:
    build: ./backend/user-service
    ports:
      - "5001:5001"
    env_file:
      - ./backend/user-service/.env

  booking-service:
    build: ./backend/booking-service
    ports:
      - "5002:5002"
    env_file:
      - ./backend/booking-service/.env
