name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'grupp_project/backend/api-gateway/**'

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'grupp_project/backend/api-gateway'

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY_LOGIN_SERVER: ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER }}
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 19.9.0
          cache: 'npm'
          cache-dependency-path: 'grupp_project/backend/api-gateway/package-lock.json' # Path to package-lock.json in video-storage subfolder.

      - name: Build
        run: docker build -t $CONTAINER_REGISTRY_LOGIN_SERVER/api-gateway:$VERSION --file ./Dockerfile .

      - name: Publish
        run: |
          echo $CONTAINER_REGISTRY_PASSWORD | docker login $CONTAINER_REGISTRY_LOGIN_SERVER --username $CONTAINER_REGISTRY_USERNAME --password-stdin
          docker push $CONTAINER_REGISTRY_LOGIN_SERVER/api-gateway:$VERSION

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ serets.KUBE_CONFIG }}
          kubectl-version: v1.24.2

      - name: Deploy Configmap
        run: envsubst < grupp_project/k8s-manifests/configmap-api-gateway.yaml | kubectl apply -f -

      - name: Deploy Secret
        run: envsubst < grupp_project/k8s-manifests/secret-api-gateway.yaml | kubectl apply -f -

      - name: Deploy Service
        run: envsubst < grupp_project/k8s-manifests/api-gateway-service.yaml | kubectl apply -f -

      - name: Deploy Deployment
        run: envsubst < grupp_project/k8s-manifests/api-gateway-deployment.yaml | kubectl apply -f -
