name: Booking Service CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'grupp_project/backend/booking-service/**'
      
jobs:
  build-and-deploy:
    name: Build, Push & Deploy Booking Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'grupp_project/backend/booking-service'

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY_LOGIN_SERVER: ${{ secrets.CONTAINER_REGISTRY_LOGIN_SERVER }}
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

    steps:
      - name:  Checkout Repository
        uses: actions/checkout@v4

      - name:  Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 19.9.0
          cache: 'npm'
          cache-dependency-path: 'grupp_project/backend/booking-service/package-lock.json'

      - name:  Install Dependencies
        run: npm install

      - name:  Build Docker Image
        run: |
          docker build -t $CONTAINER_REGISTRY_LOGIN_SERVER/booking-service:$VERSION --file ./Dockerfile .

      - name:  Push Docker Image
        run: |
          echo $CONTAINER_REGISTRY_PASSWORD | docker login $CONTAINER_REGISTRY_LOGIN_SERVER --username $CONTAINER_REGISTRY_USERNAME --password-stdin
          docker push $CONTAINER_REGISTRY_LOGIN_SERVER/booking-service:$VERSION

      - name:  Setup Kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2

      - name: Deploy ConfigMap
        run: envsubst < ../../k8s-manifests/configmap-booking-service.yaml | kubectl apply -f -

      - name: Deploy Secret
        run: envsubst < ../../k8s-manifests/secret-booking-service.yaml | kubectl apply -f -

      - name:  Deploy Service
        run: envsubst < ../../k8s-manifests/booking-service-service.yaml | kubectl apply -f -

      - name:  Deploy Deployment
        run: envsubst < ../../k8s-manifests/booking-service-deployment.yaml | kubectl apply -f -

      - name:  Verify Deployment
        run: kubectl rollout status deployment/booking-service
